JSTL/src/beans/Testbeans.java
package beans;

public class Testbeans {
   public String getInfo(){
	   return "Hello from beans";
   }
}

JSTL/src/beans/User.java
package beans;

public class User {
	private String username;
	private int id;
	
	public User(String username, int id) {
		this.username = username;
		this.id = id;
	}

	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	

}

JSTL/src/controller/Controller.java
package controller;

import java.io.IOException;
import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class Controller
 */
@WebServlet("/Controller")
public class Controller extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public Controller() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see Servlet#init(ServletConfig)
	 */
	public void init(ServletConfig config) throws ServletException {
		// TODO Auto-generated method stub
	}

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		//request.getRequestDispatcher("/Hello.jsp").forward(request, response);
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
	}

}

JSTL/WebContent/WEB-INF/Hello.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>

</body>
</html>

JSTL/WebContent/WEB-INF/jstl.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>

<body>
<jsp:useBean id="test" class="beans.Testbeans" scope="page"></jsp:useBean>
<p><c:out value="${test.info}"/></p>

</p>
<c:out value="${param.name}"/>

</p>
<c:if test='${param.name=="Josheela"}'>
Hello Josheela!
</c:if>
</p>
<c:choose>
<c:when test='${param.id=="1"}'>
<b>Param is 1</b>
</c:when>
<c:when test='${param.id=="2"}'>
<b>Param is 2</b>
</c:when>
<c:otherwise>Param is neither 1 nor 2</c:otherwise>
</c:choose>

<c:forEach var="i" begin="1" end ="10" step="2" varStatus="status">

</br>Counter is :<c:out value="${i}"/>
<c:if test="${status.first}">This is the first iteration</c:if>
<c:if test="${status.last}">This is the last iteration</c:if>
</c:forEach>



</body>
</html>

JSTL/WebContent/WEB-INF/receiveObjects.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>

<c:out value="${user1.username}"></c:out></br>
<c:out value="${user2.username}"></c:out></br>
<c:out value="${user3.username}"></c:out></br>
<c:out value="${user4.username}"></c:out></br>

<c:out value="${sessionScope.user2.username}"></c:out>
<c:out value="${requestScope.user1.username}"></c:out>
</br>
<c:out value='${map["Fruit"]}'></c:out>
</br>
${Link}
</br>

<c:forEach var="animal" items="${list1}">
  ${animal.id} :   ${animal.username}</br>
</c:forEach>

<table style="border:2px solid green">
<c:forEach var="animal" items="${list1}">
<tr>
  <td style="border:2px solid blue">${animal.id}</td><td style="border:2px solid blue">${animal.username}</td>
  </tr>
</c:forEach>

</table>



</body>
</html>